kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{ .Release.Name }}-bg"
spec:
  host: {{ .Values.route.host | default "" }}
  to:
    kind: Service
    name: {{ .Values.route.blueStack }}
    weight: 100
  alternateBackends:
  - kind: Service
    name: {{ .Values.route.oldBlueStack | default "nil" }}
    weight: 0
  port:
    targetPort: {{ .Values.route.targetPort }}
  tls:
    termination: edge
  wildcardPolicy: None
