name: Helm Publish

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.7.0'

      - name: Package and index Helm charts
        run: |
          mkdir -p build
          helm repo index build --url "https://pnminh.github.io/helm-repo"
          for dir in ./* ; do
            echo $dir
            if [ -f "$dir/Chart.yaml" ]; then
              helm dependency update "$dir"
              helm package -d build "$dir"
            fi
          done

      - name: Clone Helm repository
        uses: actions/checkout@v3
        with:
          repository: pnminh/helm-repo
          ref: main
          path: helm-repo

      - name: Copy packages and index file
        run: |
          cp -r build/* helm-repo/
          rm -rf build

      - name: Commit and push changes
        run: |
          cd helm-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Helm charts and index" || exit 0
          git config --unset-all http.https://github.com/.extraheader
          git push https://github.com/pnminh/helm-repo.git main
